menu:
  Home: /
#  カテゴリーへのリンク: /categories/essay/
  Archives: /archives

widgets:
- search
- tag
- twitter
- recent_posts

excerpt_link: Read More

twitter:
  username: myokoo21
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid: ra-568a5f688410a7bb
#  weibo: false
#  linkedin: false
#  google: true
#  facebook: true
#  twitter: true

copyright:
  enable: true
  claim: (C) 2015 MizukiYokoo.
  show_link: false

fancybox: true

google_analytics: UA-71964299-1
analytics_site_name: myokoo.github.io
rss:
